# Generated by Django 3.1.5 on 2021-01-19 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FIRSTAPPLICATION', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='id',
            name='contact',
            field=models.IntegerField(),
        ),
    ]
