# Generated by Django 3.1.5 on 2021-01-27 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_posts', '0002_auto_20210127_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='Address',
            field=models.CharField(default='None', max_length=70),
            preserve_default=False,
        ),
    ]
